// Show that Files are Connected: 
console.log("Connected...Running...");

// Declaration of Variables:
const wrapping = document.querySelector('.wrapping');
const searchButton = document.querySelector('.searchSpace button');
const weatherData = document.querySelector('.weatherData');
const weatherDetails = document.querySelector('.weatherDetails');
const error404 = document.querySelector('.notFound');

// Adding Event Lister to the Search Button:
searchButton.addEventListener('click', () =>{
    // The API key generated by the API site:
    const apiKey = '50059543581da4dbafeb896340061638';
    // getting the search value as the variable "city":
    const city = document.querySelector('.searchSpace input').value;
    console.log(city);

    if (city === ''){
        return;
    }

    // Fetching the data using the API:
    fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${apiKey}`)
        .then(response => response.json())
        .then(json => {
        if(json.cod === '404'){
            wrapping.style.height = '400px';
            weatherData.style.display = 'none';
            weatherDetails.style.display = 'none';
            error404.style.display = 'block';
            return;
        }

        // Hides the Error Message when there is No error:
        error404.style.display = 'none';

        // Getting the data and detail Divs as Variables:
        const image = document.querySelector('.weatherData img');
        const temp = document.querySelector('.weatherData .temp');
        const desc = document.querySelector('.weatherData .description');
        const humid = document.querySelector('.weatherDetails .humidity span');
        const wind = document.querySelector('.weatherDetails .wind span');

        // Switch-Cases to determine what MultiMedia to display: 
        switch (json.weather[0].main){
            case 'Clear':
                image.src = 'MultiMedia/clear.png';
                break;

            case 'Rain':
                image.src = 'MultiMedia/rain.png';
                break;

            case 'Snow':
                image.src = 'MultiMedia/snow.png';
                break;

            case 'Clouds':
                image.src = 'MultiMedia/cloud.png';
                break;

            case 'Haze':
                image.src = 'MultiMedia/mist.png';
                break;

            default:
                image.src = '';
        }

        temp.innerHTML = `${parseInt(json.main.temp)}<span>°C</span>`;
        desc.innerHTML = `${json.weather[0].description}`;
        humid.innerHTML = `${json.main.humidity}%`;
        wind.innerHTML = `${parseInt(json.wind.speed)}Km/h`;

        weatherData.style.display = '';
        weatherDetails.style.display = '';
        weatherData.classList.add('fadeIn');
        weatherDetails.classList.add('fadeIn');
        wrapping.style.height = '665px';
    });
});